---
Name: gdpr-basics
---
PageController:
  extensions:
    - TimeZoneOne\GDPR\Extension\CookieConsent

SiteConfig:
  extensions:
    - TimeZoneOne\GDPR\Extension\SiteConfigGDPR

LeftAndMain:
  extra_requirements_css:
    - gdpr-basics/admin.css

UserForm:
  extensions:
    - TimeZoneOne\GDPR\Extension\UserFormExtensionGDPR
