---
Name: gdpr-basics
---
PageController:
  extensions:
    - TimeZoneOne\GDPR\Extension\CookieConsent

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - TimeZoneOne\GDPR\Extension\SiteConfigGDPR

LeftAndMain:
  extra_requirements_css:
    - gdpr-basics/admin.css

SilverStripe\UserForms\Form\UserForm:
  extensions:
    - TimeZoneOne\GDPR\Extension\UserFormExtensionGDPR
