---
Name: gdpr-basics
---

Page_Controller:
  extensions:
    - CookieConsent

SiteConfig:
  extensions:
    - SiteConfigGDPR

LeftAndMain:
  extra_requirements_css:
    - gdpr-basics/admin.css

UserForm:
  extensions:
    - UserFormExtensionGDPR